author: Joshua Thijssen
email: jthijssen@saffire-lang.org
highlighter: pygments
github: [Repository metadata]
permalink: /:categories/:title.html
baseurl: "/saffire-docs/"
url: http://saffire.github.com
