author: Joshua Thijssen
email: jthijssen@saffire-lang.org
highlighter: pygments
github: [Repository metadata]
permalink: /:categories/:title.html
baseurl: "/saffire-docs"
url: http://saffire.github.io
github_username: saffire
twitter_username: "@saffire-lang"
disqus: true
